server {
  listen 80;
  server_name _;

  # Frontend (Quasar/PWA) estático
  root   /usr/share/nginx/html;
  index  index.html;

  # Single Page App: fallback para index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # API -> backend Node
  location /api/ {
    proxy_pass         http://izing-backend:9000;  # usa o nome do serviço no docker network
    proxy_http_version 1.1;
    proxy_set_header   Host              $host;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   Upgrade           $http_upgrade;
    proxy_set_header   Connection        "upgrade";
    proxy_read_timeout 3600s;
  }

  # WebSocket (Socket.IO)
  location /socket.io/ {
    proxy_pass         http://izing-backend:9000/socket.io/;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade           $http_upgrade;
    proxy_set_header   Connection        "upgrade";
    proxy_set_header   Host              $host;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_read_timeout 3600s;
  }

  client_max_body_size 20m;

  # (opcional) gzip básico
  gzip on;
  gzip_types text/plain text/css application/json application/javascript application/xml image/svg+xml;
  gzip_vary on;
}
